import json
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[1]


def test_f31r1_preserves_first_pass_and_uses_counterfactual_effects():
    path = ROOT / "tests" / "fixtures" / "f31r1_counterfactual_causal_reclassification.json"
    if not path.is_file():
        pytest.skip("F31R1 evidence is generated by the corrective audit")
    result = json.loads(path.read_text(encoding="utf-8"))
    assert result["production_changed"] is False
    assert result["corrected_next_boundary"] == "F32_SEARCH_HORIZON_AND_QUIESCENCE_DIAGNOSIS"
    assert result["aggregate_effects"]["0.5"]["root_tactical_effect"]["roots_gaining_depth"] == 0
    assert result["aggregate_effects"]["0.5"]["qsearch_effect"]["roots_gaining_depth"] == 10
    assert result["causal_families"]["root_tactical_scan_computational_overhead"]["label"] == "NOT_SUPPORTED"
    assert result["causal_families"]["qsearch_computational_cost"]["label"] == "PRIMARY"
    assert result["causal_families"]["native_capability_gating"]["status"] == "NATIVE_COUNTERFACTUAL_UNAVAILABLE"
    assert all(result["flags"].values())
