"""Freeze the F41 semantic material-prior audit protocol."""
from __future__ import annotations
import argparse, hashlib, json, subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/"tests"/"fixtures"/"f41_semantic_prior_manifest.json"
def bind(p): return {"path":p,"sha256":hashlib.sha256((ROOT/p).read_bytes()).hexdigest()}
def canonical(x): return json.dumps(x,sort_keys=True,separators=(",",":"))
def make():
    paths=["tests/fixtures/f40_material_feature_manifest.json","tests/fixtures/f40_material_prior_audit.json","tests/fixtures/f40_feature_utilization_ledger.json","tests/fixtures/f40_learning_leverage_ledger.json","tests/fixtures/f40_native_consumption_sidecar.json","tests/fixtures/f40_material_feature_selection.json","tests/fixtures/f39_generalization_selection.json","generic_chess/ai/evaluation/profile.py","generic_chess/ai/evaluation/analyzer.py","generic_chess/ai/evaluation/mobility.py","generic_chess/ai/evaluation/movement_graph.py","generic_chess/rules/ir.py","generic_chess/rules/compiler.py","generic_chess/rules/execution.py","generic_chess/rules/western_chess.py","generic_chess/rules/standard_shogi.py","generic_chess/learning/material.py","generic_chess/learning/features.py","generic_chess/learning/tdleaf.py","generic_chess/native/compiler.py"]
    v={"schema_version":1,"kind":"F41_SEMANTIC_MATERIAL_PRIOR_CORRECTIVE","work_order":"GENERICCHESS-F41-RULE-DERIVED-MATERIAL-PRIOR-AND-SIGNAL-UTILIZATION-CORRECTIVE","baseline":{"master":"44fce4f9dfeee0ef9480597c7ab34195db984100","sandbox":"20d76c14ea2702d76439ac0f880b600dc3846a8e","f40":"20d76c14ea2702d76439ac0f880b600dc3846a8e","product_authority":"a389adc50ed42096874ee38f818584978468c6ac","shogi_fingerprint":"ac987c3ffe75d8fa885ba787c1aa7cf60e92205465bf056b12b2989674007635"},"inputs":{p:bind(p) for p in paths},"constraints":{"PRODUCTION_DIFF_ZERO":True,"NO_NEW_EVALUATOR_FEATURE":True,"NO_TRAINING":True,"NO_ALPHASHO":True,"NO_PAIRED_BENCHMARK":True,"NO_HUMAN_RATIO_FITTING":True,"NO_R37_EXPERIMENT":True,"NO_NATIVE_MIGRATION":True,"NO_SECOND_RULE_COMPILER":True},"semantic_pattern_rules":{"ordinary_geometry":["leap","ray"],"exactly_one_actor_move":True,"exclude_state_slot_postcondition":True,"allow_capture_remove":True,"conditional_record":"conditional_capability_patterns"},"frozen_algorithms":{"raw_score":"existing _raw_capability_score unchanged","normalization":"existing median/scale/round/clamp unchanged","deployment_index":"drop_freedom * drop_mobility / max(1e-12, all_square_mobility)","hand_candidate":"round(M41_board * hand_weight * D_t / median_positive_D)"},"western_bands":{"P":[1,1],"N":[2.5,3.5],"B":[2.5,3.75],"R":[4,6],"Q":[7.5,11]},"shogi_gates":{"cosine":0.95,"spearman":0.9,"pairwise_ordering":0.9,"hand_board_ratio":[0.8,1.0]},"classification":{"SEMANTIC_MATERIAL_AND_HAND_PRIOR_SUPPORTED":"F42_SEMANTIC_MATERIAL_AND_HAND_PRIOR_INTEGRATION_PROTOTYPE","SEMANTIC_MATERIAL_PRIOR_SUPPORTED_DROP_PRIOR_NOT_SUPPORTED":"F42_SEMANTIC_MATERIAL_PRIOR_INTEGRATION_PROTOTYPE","SEMANTIC_MATERIAL_PRIOR_CROSS_RULESET_FAILURE":"F42_SEMANTIC_MATERIAL_PRIOR_COMPATIBILITY_DIAGNOSIS","SEMANTIC_MATERIAL_PRIOR_INSUFFICIENT":"F42_SEMANTIC_CAPABILITY_PRIOR_DIAGNOSIS","MIXED_OR_UNRESOLVED":"F42_GENERIC_PROFILE_PRIOR_REASSESSMENT"},"flags":["F40_MATERIAL_FEATURE_GAP_CONSUMED","SEMANTIC_MOVEMENT_SOURCE_COVERAGE_AUDITED","SEMANTIC_ANALYZER_LEGACY_COMPATIBLE","WESTERN_MATERIAL_PRIOR_RETEST_COMPLETE","STANDARD_SHOGI_MATERIAL_POSITIVE_CONTROL_COMPLETE","DROP_SIGNAL_INDEPENDENCE_AUDITED","STATIC_LEARNING_SPAN_AUDITED","NEXT_SEMANTIC_PROFILE_BOUNDARY_SELECTED"]}
    v["manifest_sha256"]=hashlib.sha256(canonical(v).encode()).hexdigest(); return v
def main():
    argparse.ArgumentParser().parse_args(); v=make(); OUT.write_text(json.dumps(v,indent=2,sort_keys=True)+"\n"); print(json.dumps({"manifest_sha256":v["manifest_sha256"],"status":"PASS"})); return 0
if __name__=="__main__": raise SystemExit(main())
